version: '3.7'

services:
  api:
    container_name: api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 9998:3000
    command: pnpm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
      - redis
  postgres:
    container_name: postgres
    image: postgres:15.4-alpine3.18
    networks:
      - webnet
    ports:
      - ${POSTGRES_HOSTPORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # PG_DATA: /var/lib/postgresql/data/
    volumes:
      - pgdata:/var/lib/postgresql/data/
  redis:
    container_name: redis
    image: redis:alpine3.18
    networks:
      - webnet
    ports:
      - ${REDIS_HOSTPORT}:${REDIS_PORT}
networks:
  webnet:
volumes:
  pgdata:
